# Generated by Django 5.0 on 2023-12-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Task", "0003_alter_task_t_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="T_desc",
            field=models.TextField(default="TASK IS ADDED ON 2023-12-11"),
        ),
    ]
